### ISSUE TITLE
Data braucht Namen von Champs

### ISSUE THREAD

**Issue by HoverBaum** [The-L4U/the_l4u_homepage#1]
Über die statische API von RIOT können Splash-Arts nur mit dem Namen eines Champions abgefragt werden. Daher sollten wir die "matchobjects" um `championName` ergänzen.

Ich hab dafür erstmal eine Datei mit den Daten über alle aktuellen angelegt. Eigentlich sollten wir die aktuellste Version erfragen und dann dafür die Liste der Chas holen, um das Mapping damit zu machen

**Comment by xbjw** [comment]
Done
